### ISSUE TITLE
Try to load Credential but got null

### ISSUE THREAD

**Issue by cyxcw1** [googleapis/google-api-java-client#1208]
#### Environment details

- OS: Android 7.0
- Java version: 1.7
- google-api-java-client version: 1.18

#### Steps to reproduce

This is my code, I tried to get this `Credential`, but I got `null`.
```
    	List<String> scopes = new ArrayList<>();
        scopes.add("https://www.googleapis.com/auth/youtube");
        scopes.add("https://www.googleapis.com/auth/userinfo.profile");
        scopes.add("email");
        InputStream in = mContext.getResources().openRawResource(R.raw.client_secrets);
        Reader clientSecretReader = new InputStreamReader(in);
        GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(JSON_FACTORY, clientSecretReader);
        clientSecrets.setInstalled(clientSecrets.getInstalled().setClientId(mContext.getString(R.string.YoutubeClientId)));

        String projectRoot = getProjectsVideoDir();
        FileDataStoreFactory fileDataStoreFactory = new FileDataStoreFactory(new File(projectRoot + "/googleOauth/" + CREDENTIALS_DIRECTORY));
        DataStore<StoredCredential> dataStore = fileDataStoreFactory.getDataStore("uploadVideo");

        flow = new GoogleAuthorizationCodeFlow.Builder(HTTP_TRANSPORT, JSON_FACTORY, clientSecrets, scopes)
                .setCredentialDataStore(dataStore).build();

        credential = flow.loadCredential("user"); // we got credential null here
```
The code is very old, it worked before and my Youtube Client id is OK.

Thank you very much.

**Comment by cyxcw1** [comment]
Can some one here help me? Thanks very much.

**Comment by mxlevin** [comment]
If Credential is null, could be because the File DataStore directory pointed to (viz. projectRoot + "/googleOauth/ + Credentials_Directory doesn't have a StoredCredential file , or one corresponding to "uploadVideo" -  In this case try the following

                        replace  
                     Credential credential = flow.loadCredential("user"); // we got credential null here
             with this 
                    Credential credential = new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");
   This may require upgrading your  google-api-java-client version to a later version , 1.25.0 or greater
  First time this will result in browser requesting a sign in and authorization based on your googleId.

If this doesn't work, check that your client_secrets.json file pointed to by R.raw.client_secrets exists and is valid.
If not refer to this URI  https://developers.google.com/youtube/v3/guides/auth/installed-apps to recreate it.

**Comment by sduskis** [comment]
@cyxcw1, sorry for the late answer.  Hopefully this helped.  I'm going to close this issue.  Please open a new issue if this isn't satisfactory.
