### ISSUE TITLE
i'm struck on create request for the method "licenseAssignments.get"

### ISSUE THREAD

**Issue by hari1692** [googleapis/google-api-java-client#1538]
Thanks for stopping by to let us know something could be better!

Please be sure to include as much information as possible:

#### Environment details

- OS:mac
- Java version:8
- google-api-java-client version:

#### Steps to reproduce

1. Can someone help me get user's license by product SKU?
I'm trying to create request for license assignments but not able to understand how to implement it.

#### Stacktrace

```
Any relevant stacktrace here.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by hari1692** [comment]
It's been a week. Can someone help me out?

**Comment by hari1692** [comment]
@chingor13 can you or someone help me out?

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
