### ISSUE TITLE
Connecting to BigQuery using Informatica DEI through enterprise (income.com.ag) physical proxy server.

### ISSUE THREAD

**Issue by stevenzhang-support** [googleapis/google-api-java-client#1832]
**Is your feature request related to a problem? Please describe.**
We Encountered proxy certificate validation issue for BigQuery connection from informatica DEI (Data Engineering Integration),as the connection jar at Informatica server/client is not updated with our enterprise ([income.com.sg](url)) proxy certificate.

**Describe the solution you'd like**
Need help from the google-api-java-client support team to update `google-api-client-1.22.0.jar` [1] with our enterprise proxy certificates added for google sites.
[1] https://mvnrepository.com/artifact/com.google.api-client/google-api-client/1.22.0

**Describe alternatives you've considered**
Please kindly advise if there is any workaround if this feature cannot be supported

**Additional context**
The enterprise ([income.com.sg](url)) proxy certificate is available to be added upon request here.

**Comment by stevenzhang-support** [comment]
Thanks for update if this is anything that eng team can accept to help with customer's private certificate

**Comment by stephaniewang526** [comment]
Hi,

There is an existing way to specify custom http transport in BigQueryOptions in order to make a call to create newTrustedTransport:
https://github.com/googleapis/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.java#L71

Upon searching, I was able to find an example resolution snippet from a similar issue that was raised a while ago (https://github.com/googleapis/google-api-java-client/issues/1114):

```
HttpTransportFactory transportFactory = () -> {
  // TODO: handle IOException, GeneralSecurityException
  InputStream inputStream = new FileInputStream("/path/to/keystore");
  String storePass = "some passcode";
  return new NetHttpTransport.Builder()
      .trustCertificatesFromJavaKeyStore(inputStream, storePass).build();
};
HttpTransportOptions transportOptions = HttpTransportOptions.newBuilder()
    .setHttpTransportFactory(transportFactory)
    .build();
BigQuery bigquery = BigQueryOptions.newBuilder()
    .setTransportOptions(transportOptions)
    .build().getService(); 
```

Please give it a try.

**Comment by stephaniewang526** [comment]
Please re-open this bug or raise new bug in java-bigquery repo if needed.
