### ISSUE TITLE
GoogleIdTokenVerifier.verify returns connect timed out

### ISSUE THREAD

**Issue by zhangmm-2024** [googleapis/google-api-java-client#2510]
<dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>com.google.http-client</groupId>
    <artifactId>google-http-client-jackson2</artifactId>
    <version>1.44.1</version>
</dependency>

**Comment by zhumin8** [comment]
Thank you for reporting. At first glance, this sounds like either a server side issue or network connection issue. It is hard to debug without any more details.

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Feel free to reopen if you believe it is a bug on the client side code, and provide a simple reproducer so we can debug.
